FROM golang:1.26

# Set working directory
WORKDIR /app

# Install Air (for hot reloading)
RUN go install github.com/air-verse/air@latest

# Copy go mod files first (for caching)
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build & run the golang app on port :8080 using Air
RUN go build -o main .
EXPOSE 8080
CMD ["air"]